const CertificateFooter = () => {
  return (
    <div className="mt-1 border-t-2 border-[#c8a34d] pt-1.5">
      <div className="grid grid-cols-2 gap-3">
        <div className="text-center">
          <div className="mx-auto h-6 w-36 border-b border-dashed border-gray-400"></div>
          <h3 className="mt-0.5 text-[11px] font-semibold text-[#081c24]">
            Authorized Appraiser
          </h3>
          <p className="text-[9px] text-gray-500">Signature & Name</p>
        </div>

        <div className="text-center">
          <div className="mx-auto flex h-8 w-8 items-center justify-center rounded-full border-2 border-dashed border-[#b8903d]">
            <span className="text-[7px] font-semibold leading-3 text-[#b8903d]">
              Institute
              <br />
              Seal
            </span>
          </div>
          <h3 className="mt-0.5 text-[11px] font-semibold text-[#081c24]">
            Official Seal
          </h3>
        </div>
      </div>

      <div className="mt-1.5 rounded-lg bg-[#faf7ef] px-3 py-1.5">
        <h3 className="mb-0.5 text-[11px] font-bold text-[#b8903d]">
          Certificate Verification
        </h3>
        <p className="text-[10px] leading-3 text-gray-700">
          This certificate has been generated by the
          <strong>
            {" "}
            Indian Institute of Precious Gem & Jewellery Appraisers (IIPGJA)
          </strong>{" "}
          using the Density Method and Touch Stone Surface Colour Method.
        </p>
      </div>

      <div className="mt-1.5 grid grid-cols-2 gap-3 text-center text-[10px]">
        <div>
          <h4 className="font-semibold text-[#081c24]">Website</h4>
          <p className="text-gray-600">www.iipgja.org</p>
        </div>
        <div>
          <h4 className="font-semibold text-[#081c24]">Email</h4>
          <p className="text-gray-600">iipgja.contact@gmail.com</p>
        </div>
      </div>

      <p className="mt-1.5 pb-0.5 text-center text-[10px] font-semibold leading-4 text-[#081c24]">
        © {new Date().getFullYear()} IIPGJA - Indian Institute of Precious Gem
        & Jewellery Appraisers. All Rights Reserved.
      </p>
    </div>
  );
};

export default CertificateFooter;
